name: iprovis
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  image: ^3.2.2
  camera: ^0.11.1
  image_picker: ^1.1.2
  http: ^1.3.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/iprovis_model_v4.tflite
    - assets/labels.txt
    - assets/images/
